### ISSUE TITLE
Align "1 point possible" 

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#1]
We want to move that text to right so that it can't be confusion among question text and options/images.
![16443442_1742256715800047_790498102_n](https://cloud.githubusercontent.com/assets/13884387/22507327/e5db1494-e8a6-11e6-9656-aa3b2bf1d872.png)

See attachment 
@amir-qayyum-khan

**Comment by aqdasrehman** [comment]
@amir-qayyum-khan  We need to hide this now instead of moving it to right.

**Comment by amir-qayyum-khan** [comment]
removed

**Comment by amir-qayyum-khan** [comment]
Done, please verify @aqdasrehman http://54.86.197.122/

**Comment by aqdasrehman** [comment]
@amir-qayyum-khan I can still see this "1 Point Possible" 
see attachment 
![screen shot 2017-02-03 at 6 57 17 pm](https://cloud.githubusercontent.com/assets/13884387/22593935/b7bb7c1e-ea42-11e6-96db-fd5507a65429.png)

**Comment by aqdasrehman** [comment]
This is Done, Closing this issue.
