### ISSUE TITLE
Remove Bookmarks functionality

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#15]
We need to remove bookmarks functionality

**Comment by amir-qayyum-khan** [comment]
Done

**Comment by amir-qayyum-khan** [comment]
Done, please verify @aqdasrehman http://54.86.197.122/

**Comment by aqdasrehman** [comment]
@amir-qayyum-khan Bookmarks button is still showing, See attachment : 

![screen shot 2017-02-05 at 1 14 45 am](https://cloud.githubusercontent.com/assets/13884387/22621235/94c35034-eb40-11e6-9b37-eaea6136f26e.png)

**Comment by amir-qayyum-khan** [comment]
please verify

**Comment by aqdasrehman** [comment]
This is done. Closing
