### ISSUE TITLE
Checking shouldn't show to students

### ISSUE THREAD

**Issue by aqdasrehman** [amir-qayyum-khan/edx-platform#63]
After submitting answer there is a "Checking" text shown to students which shouldn't be
See video on the link : https://screencast.com/t/PQA7cknrUkz

**Comment by aqdasrehman** [comment]
Make that text "Checking" to "Submitting"

**Comment by naeem91** [comment]
Fixed. Please verify

**Comment by aqdasrehman** [comment]
Checking text is still showing, please see video. https://screencast.com/t/dUIzGm9Ou1Sv

**Comment by naeem91** [comment]
@aqdasrehman sorry wasn't merged back then. Please verify now

**Comment by aqdasrehman** [comment]
Done. Closing
